sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t balukarnam92/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true balukarnam92/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-147125738351'
  bucket_path: 'docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
